### ISSUE TITLE
When execute the build could perform uglify

### ISSUE THREAD

**Issue by caueops** [lyef/lyef-react-component#7]
If we think in the way: `plug & play` it's really necessary to minify for reduce the file size.

I'm not familiar with the command line of `babel` but I saw that we can use plugins, like: https://www.npmjs.com/package/babel-plugin-uglify

Or it's possible too with task runner, like gulpjs.

**Comment by willianjusten** [comment]
You're right, but I was thinking about it...
If they use our component on their application, they will uglify the code when build to production. This means that we're doing something that they will do later...

But if they don't uglify their code and we did it, we're doing our part to best performance...

**Comment by jmpas** [comment]
I'm working on this, I'm minifying and uglifying but I'm not adding the minified version as `main` in `package.json`.

ref lyef/lyef-react-counter#15

What do you guys think? I'm basically adding this just for showing what the component's size will be like, when using it in production (minified and uglified)
